# Generated by Django 3.1.5 on 2021-04-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_helps_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='helps_received',
            name='customer_contact_no',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helps_received',
            name='customer_email',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helps_received',
            name='customer_latitude',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helps_received',
            name='customer_longitude',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
