# Generated by Django 3.1.5 on 2021-04-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_location_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='helps_received',
            name='customer_description',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
