# Generated by Django 3.1.7 on 2021-03-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0002_need_help'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
