# Generated by Django 3.1.5 on 2021-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0003_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='need_help',
            name='latitude',
            field=models.CharField(default='default_testing', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='need_help',
            name='longitude',
            field=models.CharField(default='default_testing', max_length=200),
            preserve_default=False,
        ),
    ]
