# Generated by Django 3.1.5 on 2021-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0005_need_help_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='helps_finished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('mechanic_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=50)),
                ('customer_contact_no', models.CharField(max_length=50)),
                ('customer_description', models.CharField(max_length=1000)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('customer_latitude', models.CharField(max_length=200)),
                ('customer_longitude', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
