# Generated by Django 3.1.5 on 2021-04-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0006_helps_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helps_finished',
            name='created',
        ),
    ]
