# Generated by Django 3.1.5 on 2021-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0007_remove_helps_finished_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='helps_finished',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2012-05-28 11:19:42.897000+00:00'),
            preserve_default=False,
        ),
    ]
