# Generated by Django 3.1.5 on 2021-05-05 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0008_helps_finished_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helps_finished',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 19, 44, 58, 692746, tzinfo=utc)),
        ),
    ]
