# Generated by Django 3.1.5 on 2021-05-05 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0009_auto_20210506_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helps_finished',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
