# Generated by Django 3.1.5 on 2021-05-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0010_auto_20210506_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helps_finished',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
